FROM debian:wheezy
MAINTAINER Simeon van der Steen <simeon.vandersteen@bbc.co.uk>

# Add bbcarchdev apt repo
ENV DEBIAN_FRONTEND noninteractive
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 9E16A4D302DA096A && \
	echo "deb [arch=amd64] http://apt.bbcarchdev.net/debian/ wheezy main ports live stage dev" \
	>> /etc/apt/sources.list.d/bbcarchdev-wheezy.list

# Install everything needed
RUN apt-get -y update && apt-get install -y --no-install-recommends --fix-missing \
	ngrep procps tcpdump inotify-tools netcat netcat-traditional \
	build-essential libtool libltdl-dev automake \
	autoconf pkg-config libcurl4-gnutls-dev autotools-dev \
	libraptor2-dev librasqal3-dev librdf0-dev libfcgi-dev \
	libjansson-dev libssl-dev cmake itstool \
	gettext python-libxml2 libpq-dev libmysqlclient-dev valgrind \
	uuid-dev libncurses5-dev libedit-dev raptor2-utils gdb vim \
	libawsclient-dev libsparqlclient-dev \
	libquilt-dev libcluster-dev libsql-dev libmq-dev mc \
	&& rm -rf /var/lib/apt/lists/*
	
# Take care of Twine
COPY twine /usr/local/src/twine
WORKDIR /usr/local/src/twine
RUN autoreconf -i && \
	./configure --prefix=/usr --enable-debug --disable-docs && \
	make && \
	make install

# Take care of Spindle
COPY spindle /usr/local/src/spindle
WORKDIR /usr/local/src/spindle
RUN autoreconf -i && \
	./configure --prefix=/usr --enable-debug --disable-docs && \
	make && \
	make install

WORKDIR /usr/local/src/twine

# Link the config file to its actual usage location
RUN rm -f /usr/etc/twine.conf
RUN ln docker/twine-writerd.conf /usr/etc/twine.conf

ENV TERM xterm

RUN cp docker/run-writerd.sh /run.sh
ENTRYPOINT ["/run.sh"]

# Launch writerd
CMD ["/usr/sbin/twine-writerd", "-d", "-c", "/usr/etc/twine.conf", "-f"]
