FROM debian:wheezy
MAINTAINER Simeon van der Steen <simeon.vandersteen@bbc.co.uk>

# Add bbcarchdev apt repo
ENV DEBIAN_FRONTEND noninteractive
RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 9E16A4D302DA096A && \
	echo "deb [arch=amd64] http://apt.bbcarchdev.net/debian/ wheezy main ports live stage dev" \
	>> /etc/apt/sources.list.d/bbcarchdev-wheezy.list

# Build tools
RUN apt-get -y update && apt-get install -y --no-install-recommends --fix-missing \
	build-essential automake autoconf autotools-dev pkg-config libtool \
	cmake gettext \
	&& rm -rf /var/lib/apt/lists/*

# Debugging tools
RUN apt-get -y update && apt-get install -y --no-install-recommends --fix-missing \
	tcpdump ngrep procps mc vim gdb raptor2-utils valgrind \
	&& rm -rf /var/lib/apt/lists/*

# Acropolis external dependencies
RUN apt-get -y update && apt-get install -y --no-install-recommends --fix-missing \
	libraptor2-dev librasqal3-dev librdf0-dev libfcgi-dev libltdl-dev \
	libcurl4-gnutls-dev libqpid-proton-dev libjansson-dev libssl-dev \
	python-libxml2 uuid-dev libncurses5-dev libedit-dev \
	&& rm -rf /var/lib/apt/lists/*
	
# Acropolis own dependencies
RUN apt-get -y update && apt-get install -y --no-install-recommends --fix-missing \
	libawsclient-dev libsparqlclient-dev libquilt-dev libcluster-dev \
	libsql-dev libmq-dev libpq-dev libmysqlclient-dev \
	&& rm -rf /var/lib/apt/lists/*

# Additional stuff for this Docker Image
RUN apt-get -y update && apt-get install -y --no-install-recommends --fix-missing \
	netcat netcat-traditional python3-psycopg2 supervisor python3 \
	&& rm -rf /var/lib/apt/lists/*

# Copy and compile Twine
COPY twine /usr/local/src/twine
WORKDIR /usr/local/src/twine
RUN autoreconf -i && \
	./configure --prefix=/usr --enable-debug --disable-docs && \
	make && \
	make install

# Copy and compile Spindle
COPY spindle /usr/local/src/spindle
WORKDIR /usr/local/src/spindle
RUN autoreconf -i && \
	./configure --prefix=/usr --enable-debug --disable-docs && \
	make && \
	make install

# Copy and compile Twine-Anansi bridge (for the Twine plugin)
COPY twine-anansi-bridge /usr/local/src/twine-anansi-bridge
WORKDIR /usr/local/src/twine-anansi-bridge
RUN autoreconf -i && \
	./configure --prefix=/usr --enable-debug --disable-docs && \
	make && \
	make install

WORKDIR /usr/local/src/twine

# Link the config file to its actual usage location
RUN rm -f /usr/etc/twine.conf
RUN ln docker/twine-cli.conf /usr/etc/twine.conf

ENV TERM xterm

RUN cp docker/run-cli.sh /run.sh
ENTRYPOINT ["/run.sh"]

# Install the remote control
RUN cp docker/remote.py /usr/local/bin/remote.py
EXPOSE 8000

# Launch supervisord
RUN ln docker/supervisord.conf /etc/supervisor/conf.d/twine.conf
CMD ["/usr/bin/supervisord"]
